# Copyright (c) 2021, Megamind (megamind4089)
# SPDX-License-Identifier: Apache-2.0

description: PWM Buzzer node

compatible: "pwm-buzzer"

properties:
  pwms:
    type: phandle-array
    required: true

  label:
    required: false
    type: string
    description: Human readable string describing the device (used as device_get_binding() argument)
