on: [push, pull_request]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-init
        with:
          args: 'init "-l config"'
      - name: West Update
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-update
        with:
          args: 'update'
      - name: West Config Zephyr Base
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-config
        with:
          args: 'config "--global zephyr.base-prefer configfile"'
      - name: West Zephyr Export
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-zephyr-export
        with:
          args: 'zephyr-export'
      - name: West Build (cyber60_rev_a)
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-build-cyber60_rev_a
        with:
          args: 'build "-s zmk/app -p -b cyber60_rev_a -- -DZMK_CONFIG=/github/workspace/config"'
      - name: Archive (cyber60_rev_a)
        uses: actions/upload-artifact@v2
        with:
          name: cyber60_rev_a
          path: build/zephyr/zmk.uf2
      - name: West Build (cyber60_rev_b)
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-build-cyber60_rev_b
        with:
          args: 'build "-s zmk/app -p -b cyber60@B -- -DZMK_CONFIG=/github/workspace/config -DKEYMAP_FILE=/github/workspace/config/boards/arm/cyber60/cyber60.keymap"'
      - name: Generated DTS tmp file
        if: always()
        run: cat -n build/zephyr/cyber60.dts.pre.tmp
      - name: Generated DTS file
        if: always()
        run: cat -n build/zephyr/zephyr.dts
      - name: Archive (cyber60_rev_b)
        uses: actions/upload-artifact@v2
        with:
          name: cyber60_rev_b
          path: build/zephyr/zmk.uf2
      - name: West Build (cyber60_rev_c)
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-build-cyber60_rev_c
        with:
          args: 'build "-s zmk/app -p -b cyber60@C -- -DZMK_CONFIG=/github/workspace/config -DKEYMAP_FILE=/github/workspace/config/boards/arm/cyber60/cyber60.keymap"'
      - name: Generated DTS tmp file
        if: always()
        run: cat -n build/zephyr/cyber60.dts.pre.tmp
      - name: Generated DTS file
        if: always()
        run: cat -n build/zephyr/zephyr.dts
      - name: Archive (cyber60_rev_c)
        uses: actions/upload-artifact@v2
        with:
          name: cyber60_rev_c
          path: build/zephyr/zmk.uf2
